FROM node:20-alpine AS angular_build

WORKDIR /app

COPY ./webjet-movies-web-app/package.json ./webjet-movies-web-app/package-lock.json ./

RUN npm install

COPY ./webjet-movies-web-app/. .

RUN npm run build -- --configuration production

FROM nginx:alpine AS angular_serve

COPY ./webjet-movies-web-app/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=angular_build /app/dist/webjet-movies-web-app/browser /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]