version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  cinamWorldDataSync:
    build:
      context: .
      dockerfile: ./CinemaWorldDataSync/Dockerfile
    image: cinemaworlddatasync
    container_name: cinemaWorldDataSync
    depends_on:
      - redis
    env_file:
      - "./.env"
    environment:
      - RedisConfigOption__ConnectionString=${RedisConfigOption__ConnectionString}
      - CinemaWorldConfigurationOption__CinemaMovieHttpClientName=${CinemaWorldConfigurationOption__CinemaMovieHttpClientName}
      - CinemaWorldConfigurationOption__BaseUrl=${CinemaWorldConfigurationOption__BaseUrl}
    secrets:
        - CinemaWorldConfigurationOption__AccessToken
secrets:
  CinemaWorldConfigurationOption__AccessToken:
   file: ./secrets/CinemaWorldConfigurationOption__AccessToken.txt